version: "2"
services:
  devel:
    build: .
    working_dir: /home/node
    volumes:
      - ./js/accessories:/home/node/node_modules/hap-nodejs/accessories
      - ./js:/home/node/js
    command: "/bin/bash"
  test:
    build: .
    working_dir: /home/node/js
    volumes:
      - ./js:/home/node/js
    command: "npm run lint && npm run test"
  hap-nodejs:
    build: .
    working_dir: /home/node
    volumes:
      - ./js/accessories:/home/node/node_modules/hap-nodejs/accessories
    command: /bin/bash -c "service dbus start && service avahi-daemon start && npm install && node node_modules/hap-nodejs/Core.js"