version: "2"
services:
  devel:
    build: .
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./js:/home/node/app
    expose:
      - "8081"
    command: "tail -f /dev/null"
  test:
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./js:/home/node/app
    command: "npm test"
