version: "2"
services:
  devel:
    build: .
    #user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./js:/home/node/app
    command: "/bin/bash"
  test:
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./js:/home/node/app
    command: "npm run lint && npm test"
  hap-nodejs:
    build: .
    working_dir: /home/node/HAP-NodeJS
    volumes:
      - ./js:/home/node/HAP-NodeJS/accessories
    command: /bin/bash -c "service dbus start && service avahi-daemon start && npm install && node Core.js"